# Run CI=false && yarn deploy:github
# yarn run v1.22.19
# $ gh-pages -d build
# Cloning into '/home/runner/work/stock-market-fe/stock-market-fe/node_modules/.cache/gh-pages/https!github.com!ngodanghai9x!stock-market-fe'...
# fatal: could not read Username for 'https://github.com': No such device or address

# error Command failed with exit code 1.
# info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
# Error: Process completed with exit code 1.

# Run CI=false && yarn deploy:github
# yarn run v1.22.19
# $ gh-pages -d build
# fatal: could not read Username for 'https://github.com': No such device or address

# error Command failed with exit code 1.
# info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
# Error: Process completed with exit code 1.
# =========================================================================

# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  pull_request:
    types:
        - opened
        - labeled
        - synchronize
        - reopened
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-gitHub-pages:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: git config --global user.email "ndh9x@cicd.com"
      - run: git config --global user.name "ndh9x cicd"
      - run: CI=false && yarn build
      - name: Deploy to GitHub Pages
        run: CI=false && yarn deploy:github
      
